apiVersion: bctl.mirantis.com/v1alpha1
kind: Blueprint
metadata:
  name: lens-appiq-cluster
spec:
  kubernetes:
    provider: k0s
    version: v1.28.3+k0s.0
    infra:
      hosts:
      - ssh:
          # Update address and keyPath
          address: 127.0.0.1
          keyPath: $HOME/.lima/_config/user
          port: 60022
          user: $USER
        role: single
  components:
    addons:
      - name: lens-appiq
        kind: chart
        enabled: true
        namespace: shipa-system
        chart:
          name: shipa
          repo: https://lensappiq-charts.storage.googleapis.com
          version: 0.1.0
          values: |
            auth:
              adminUser: "admin" # Required. This should be changed
              adminPassword: "Pass123$" # Required. This should be changed. It must include letters, numbers, and symbols
            shipaCluster:
              ingress:
                # SERVICE_TYPE can be ClusterIP or NodePort or LoadBalancer (default)
                serviceType: ClusterIP
